const KEY='leiqiu_vocab_v2',OLD_KEY='leiqiu_vocab_v1',TOTAL=WORDS.length,DAILY_NEW=10,DAILY_DUE_CAP=20;
let saved=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||'{}');
let state={mode:'cards',sessionType:'',list:[],i:0,revealed:false,checked:false,results:[],summary:null};
const $=s=>document.querySelector(s),study=$('#study');
const todayKey=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const addDays=n=>Date.now()+n*86400000;
const shuffle=a=>a.slice().sort(()=>Math.random()-.5);
function rec(id){let r=saved[id]||(saved[id]={seen:0,wrong:0,stage:0,due:0,lastCorrectDay:'',stable:false});if(r.stage==null)r.stage=r.mastered?4:Math.min(r.streak||0,3);r.seen=r.seen||0;r.wrong=r.wrong||0;r.due=r.due||0;r.lastCorrectDay=r.lastCorrectDay||'';r.stable=r.stage>=5;r.mastered=r.stage>=4;return r}
const meta=()=>saved.__meta||(saved.__meta={studyStreak:0,lastDay:''});
function touchDay(){let m=meta(),today=todayKey();if(m.lastDay===today)return;if(!m.lastDay)m.studyStreak=1;else{let [y,mo,d]=m.lastDay.split('-').map(Number),prev=new Date(y,mo-1,d),now=new Date();prev.setHours(0,0,0,0);now.setHours(0,0,0,0);m.studyStreak=Math.round((now-prev)/86400000)===1?m.studyStreak+1:1}m.lastDay=today}
function persist(){localStorage.setItem(KEY,JSON.stringify(saved));stats()}
function entries(){return Object.entries(saved).filter(([k])=>k!=='__meta').map(([id])=>rec(id))}
function isDue(r){return r.seen>0&&r.stage<5&&r.due<=Date.now()}
function stats(){let a=entries(),mastered=a.filter(x=>x.stage>=4).length,stable=a.filter(x=>x.stage>=5).length;$('#total').textContent=TOTAL;$('#journeyTotal').textContent=TOTAL;$('#learned').textContent=a.filter(x=>x.seen).length;$('#due').textContent=a.filter(isDue).length;$('#mastered').textContent=mastered;$('#stable').textContent=stable;$('#streak').textContent=meta().studyStreak||0;renderJourney(mastered);renderBadges(mastered);updateTodayPanel()}
function renderJourney(n){let pct=Math.min(100,n/TOTAL*100),next=[50,100,300,600,1000,TOTAL].find(x=>x>n);$('#journeyCount').textContent=n;$('#journeyFill').style.width=pct+'%';$('#journeyTitle').textContent=n>=TOTAL?'成功登顶！':n>=1000?'正在冲刺峰顶':n>=600?'越过高山线':n>=300?'到达半山营地':n>=100?'进入稳定节奏':n>=50?'抵达第一营地':'从山脚出发';$('#journeyHint').textContent=next?`再掌握${next-n}词，解锁${next}词徽章`:`${TOTAL}词全部掌握，了不起！`}
function renderBadges(n){let names={50:'起步',100:'百词',300:'坚持',600:'半山',1000:'千词',[TOTAL]:'登顶'};$('#badges').innerHTML=Object.keys(names).map(x=>`<div class="badge ${n>=x?'earned':''}" title="掌握${x}词">${names[x]}<br>${x}</div>`).join('')}
function options(){let grades=[...new Set(WORDS.map(x=>x.grade).filter(Boolean))].sort();$('#grade').innerHTML='<option value="">全部年级</option>'+grades.map(x=>`<option>${x}</option>`).join('');refreshUnits()}
function refreshUnits(){let g=$('#grade').value,old=$('#unit').value,units=[...new Set(WORDS.filter(x=>!g||x.grade===g).map(x=>x.unit).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));$('#unit').innerHTML='<option value="">全部单元</option>'+units.map(x=>`<option>${x}</option>`).join('');if(units.includes(old))$('#unit').value=old}
function filteredWords(){let g=$('#grade').value,u=$('#unit').value;return WORDS.filter(w=>(!g||w.grade===g)&&(!u||w.unit===u))}
function todayPlan(){let all=filteredWords(),newWords=shuffle(all.filter(w=>!saved[w.id]||!rec(w.id).seen)).slice(0,DAILY_NEW),dueWords=shuffle(all.filter(w=>saved[w.id]&&isDue(rec(w.id)))).slice(0,DAILY_DUE_CAP);return{newWords,dueWords}}
function updateTodayPanel(){if(!$('#grade'))return;let p=todayPlan(),steps=p.newWords.length*2+p.dueWords.length;$('#todayNew').textContent=p.newWords.length;$('#todayDue').textContent=p.dueWords.length;$('#todayEstimate').textContent=steps?`预计用时约${Math.max(3,Math.ceil(steps*.32))}分钟`:'今天的任务已经完成'}
function startToday(){let p=todayPlan();state.mode='today';state.sessionType='today';state.results=[];state.i=0;state.revealed=false;state.checked=false;state.summary={newCount:p.newWords.length,dueCount:p.dueWords.length,correct:0,tested:0};let due=p.dueWords.map(w=>({...w,task:'spell',source:'due'})),cards=p.newWords.map(w=>({...w,task:'cards',source:'new'})),tests=shuffle(p.newWords).map(w=>({...w,task:'spell',source:'new'}));state.list=[...due,...cards,...tests];beginSession()}
function manualPool(){let p=filteredWords();if(state.mode==='review')p=p.filter(w=>saved[w.id]&&isDue(rec(w.id)));if(state.mode==='wrong')p=p.filter(w=>saved[w.id]&&rec(w.id).wrong>0&&rec(w.id).stage<5);return shuffle(p).slice(0,+$('#limit').value)}
function startManual(){state.sessionType='manual';state.results=[];state.i=0;state.revealed=false;state.checked=false;state.summary={newCount:0,dueCount:0,correct:0,tested:0};let task=state.mode==='cards'?'cards':state.mode==='listen'?'listen':'spell';state.list=manualPool().map(w=>({...w,task,source:'manual'}));beginSession()}
function beginSession(){$('.session').classList.add('show');renderTrack();render()}
function showWelcome(){$('.session').classList.remove('show');study.classList.remove('celebrate');study.innerHTML='<div class="welcome"><img src="mascot.png" alt=""><h2>今天也一起向山顶前进吧</h2><p>点击“开始今日任务”，系统会先安排到期复习，再学习新词。</p></div>'}
function renderTrack(){if(!state.list.length){$('#sessionTrack').innerHTML='';return}$('#sessionTrack').innerHTML=state.list.map((_,i)=>`<i class="${state.results[i]===true?'good-dot':state.results[i]===false?'bad-dot':state.results[i]==='view'?'view-dot':''}"></i>`).join('')}
function speechText(raw){return raw.replace(/\s*\([^)]*\)\s*/g,' ').replace(/\b(sb|sth)\.?\b/gi,'something').replace(/\.{3}|…/g,' ').replace('/',' or ').trim()}
function speakWord(raw){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(speechText(raw)),voices=window.speechSynthesis.getVoices();u.voice=voices.find(v=>/^en-US/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||null;u.lang='en-US';u.rate=.78;window.speechSynthesis.speak(u)}
function soundLine(w,large=false,showIpa=true){return `<div class="pronunciation">${showIpa&&w.ipa?`<span class="ipa">/${w.ipa}/</span>`:''}<button class="sound ${large?'large':''}" onclick="speakWord(state.list[state.i].word)" aria-label="播放${w.word}的发音" title="点击发音">🔊</button></div>`}
function normalize(s){return(s||'').trim().toLowerCase().replace(/[.。]/g,'').replace(/[-‐‑–—]/g,' ').replace(/[’]/g,"'").replace(/\s+/g,' ')}
function answers(w){let raw=w.word,main=raw.replace(/\s*\([^)]*\)\s*/g,'').trim(),arr=main.includes('/')?main.split('/'): [main],ame=raw.match(/\(AmE\s+([^)]*)\)/i);if(ame)arr.push(ame[1]);return [...new Set(arr.map(normalize))]}
function currentTask(){return state.list[state.i]?.task||'cards'}
function markCard(familiar){let w=state.list[state.i],r=rec(w.id);touchDay();r.seen++;state.results[state.i]='view';if(!familiar){r.wrong++;r.stage=0;r.stable=false;r.mastered=false;r.lastCorrectDay='';r.due=addDays(1)}else if(!r.due)r.due=Date.now();persist();renderTrack();next()}
function objectiveResult(ok){let item=state.list[state.i],r=rec(item.id),today=todayKey();touchDay();r.seen++;if(!item.retry){state.summary.tested++;if(ok)state.summary.correct++}if(ok){if(item.retry){r.correctedToday=true;r.due=addDays(1)}else if(r.stage<5&&r.lastCorrectDay!==today&&(r.stage===0||r.due<=Date.now())){r.stage++;r.lastCorrectDay=today;r.due=r.stage===1?addDays(1):r.stage===2?addDays(3):r.stage===3?addDays(7):r.stage===4?addDays(14):0}r.stable=r.stage>=5;r.mastered=r.stage>=4}else{r.wrong++;r.stage=0;r.stable=false;r.mastered=false;r.lastCorrectDay='';r.due=addDays(1);if(!item.retry){let at=Math.min(state.list.length,state.i+4);state.list.splice(at,0,{...item,task:item.task==='listen'?'listen':'spell',retry:true});state.results.splice(at,0,undefined)}}state.results[state.i]=ok;persist();renderTrack()}
function next(){state.i++;state.revealed=false;state.checked=false;render()}
function render(){study.classList.remove('celebrate');if(!state.list.length||state.i>=state.list.length)return finish();let w=state.list[state.i],task=currentTask(),retry=w.retry?' · 再练一次':'';let head=`<div class="meta"><span>${state.i+1} / ${state.list.length}${retry}</span><span>${w.grade||'—'} · ${w.unit||'—'} · ${w.pos||'词组'}</span></div>`;if(task==='cards'){study.innerHTML=head+`<div class="word">${w.word}</div>${soundLine(w)}${state.revealed?`<div class="meaning">${w.meaning}</div><p class="muted">词卡只记录熟悉度，掌握状态由默写决定。</p><div class="actions"><button onclick="markCard(false)">没想起来</button><button class="primary" onclick="markCard(true)">想起来了</button></div>`:`<p class="muted">先在心里回想词义和读音</p><div class="actions"><button class="primary" onclick="state.revealed=true;render()">查看词义</button></div>`}`}else if(task==='listen'){study.innerHTML=head+`${soundLine(w,true,false)}<p class="muted">点击播放，听音写出单词或词组</p>${answerBox()}`}else{study.innerHTML=head+`${soundLine(w)}<div class="meaning">${w.pos?`<span class="muted">${w.pos}</span> `:''}${w.meaning}</div>${answerBox()}`}setTimeout(()=>$('#answer')?.focus(),0)}
function answerBox(){return `<div class="answer"><input id="answer" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="请输入英文单词或词组" aria-label="英文答案"><div id="feedback"></div></div><div class="actions"><button class="primary" id="check" onclick="checkAnswer()">核对答案</button></div>`}
function checkAnswer(){if(state.checked)return next();let w=state.list[state.i],input=$('#answer'),ok=answers(w).includes(normalize(input.value));state.checked=true;input.disabled=true;let extra=currentTask()==='listen'?`<br>${w.ipa?`<span class="ipa">/${w.ipa}/</span><br>`:''}${w.meaning}`:'';$('#feedback').innerHTML=ok?`<p class="good">正确：${w.word}${extra}</p>`:`<p class="bad">你的答案：${input.value||'（未填写）'}<br>正确答案：<b>${w.word}</b>${extra}</p>`;$('#check').textContent='下一词';objectiveResult(ok);$('#check').onclick=next}
function finish(){let completed=state.list.length&&state.i>=state.list.length;study.classList.toggle('celebrate',!!completed);if(!completed){study.innerHTML='<div class="welcome"><h2>当前范围没有可学习的词</h2><p>可以更换年级、单元或学习模式。</p></div>';return}let rate=state.summary.tested?Math.round(state.summary.correct/state.summary.tested*100):0,summary=state.sessionType==='today'?`<div class="result-card">新学 <b>${state.summary.newCount}</b> 词 · 到期复习 <b>${state.summary.dueCount}</b> 词<br>首次默写正确率 <b>${rate}%</b> · 连续学习 <b>${meta().studyStreak}</b> 天</div>`:state.summary.tested?`<div class="result-card">首次检测正确率 <b>${rate}%</b> · 本组检测 <b>${state.summary.tested}</b> 词</div>`:'';study.innerHTML=`<div class="finish-mark">✦</div><div class="word">本组完成</div><p>今天又向山顶前进了一步。</p>${summary}<div class="actions"><button onclick="downloadCard()">生成打卡图片</button><button class="primary" onclick="${state.sessionType==='today'?'startToday()':'startManual()'}">再来一组</button></div>`;stats()}
async function downloadCard(){
 let c=document.createElement('canvas');c.width=1080;c.height=1350;let x=c.getContext('2d'),rate=state.summary.tested?Math.round(state.summary.correct/state.summary.tested*100):0;
 let bg=x.createLinearGradient(0,0,1080,1350);bg.addColorStop(0,'#173579');bg.addColorStop(1,'#315ee9');x.fillStyle=bg;x.fillRect(0,0,1080,1350);
 x.globalAlpha=.12;x.fillStyle='#ffffff';x.beginPath();x.arc(1010,100,230,0,Math.PI*2);x.fill();x.beginPath();x.arc(30,1290,180,0,Math.PI*2);x.fill();x.globalAlpha=1;
 x.fillStyle='white';roundRect(x,58,56,964,1238,46);x.fill();
 x.fillStyle='#2449df';x.font='800 43px system-ui';x.fillText('蕾丘英语',110,155);x.fillStyle='#8a96af';x.font='26px system-ui';x.fillText('2027 上海中考英语词汇通关',110,200);
 x.fillStyle='#eef3ff';x.beginPath();x.arc(840,170,112,0,Math.PI*2);x.fill();let img=new Image();img.src='mascot.png';try{await img.decode();x.drawImage(img,732,68,220,204)}catch{}
 x.fillStyle='#17213d';x.font='800 68px system-ui';x.fillText('今日词汇打卡',110,335);
 x.fillStyle='#edf2ff';roundRect(x,110,365,235,56,28);x.fill();x.fillStyle='#47629f';x.font='28px system-ui';x.fillText(new Date().toLocaleDateString('zh-CN'),137,403);
 let manual=state.sessionType!=='today',baseCount=state.list.filter(w=>!w.retry).length;
 let items=manual?[["本组学习",baseCount,"词"],["首次答对",state.summary.correct,"词"],["首次正确率",state.summary.tested?rate:'—',state.summary.tested?'%':''],["连续学习",meta().studyStreak,"天"]]:[["新学词汇",state.summary.newCount,"词"],["到期复习",state.summary.dueCount,"词"],["首次正确率",rate,"%"],["连续学习",meta().studyStreak,"天"]];
 let spots=[[110,480],[555,480],[110,660],[555,660]];items.forEach((it,i)=>{let[a,b]=spots[i];x.fillStyle=i===2?'#eef3ff':'#f6f8fc';roundRect(x,a,b,415,150,25);x.fill();x.fillStyle='#73809a';x.font='27px system-ui';x.fillText(it[0],a+32,b+45);x.fillStyle=i===2?'#2449df':'#17213d';x.font='800 53px system-ui';x.fillText(String(it[1]),a+32,b+112);let width=x.measureText(String(it[1])).width;x.font='28px system-ui';x.fillText(it[2],a+42+width,b+110)});
 x.fillStyle='#eef3ff';roundRect(x,110,855,860,220,30);x.fill();x.fillStyle='#9eb1df';x.font='700 78px Georgia';x.fillText('“',145,943);x.fillStyle='#21345e';x.font='italic 700 34px Georgia';x.fillText('A little progress each day',205,950);x.fillText('adds up to big results.',205,1000);x.fillStyle='#6f7d99';x.font='27px system-ui';x.fillText('每天一点，终会汇成大进步。',205,1045);
 x.strokeStyle='#e3e8f2';x.lineWidth=2;x.beginPath();x.moveTo(110,1135);x.lineTo(970,1135);x.stroke();x.fillStyle='#2449df';x.font='700 32px system-ui';x.fillText('每天一点，记得更牢。',110,1205);x.fillStyle='#7f8ca5';x.font='24px system-ui';x.textAlign='right';x.fillText('蕾丘英语｜微信 17521631424',970,1205);x.textAlign='left';
 c.toBlob(blob=>{let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`蕾丘英语词汇打卡-${todayKey()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')
}
function roundRect(x,a,b,w,h,r){x.beginPath();if(x.roundRect){x.roundRect(a,b,w,h,r);return}x.moveTo(a+r,b);x.lineTo(a+w-r,b);x.quadraticCurveTo(a+w,b,a+w,b+r);x.lineTo(a+w,b+h-r);x.quadraticCurveTo(a+w,b+h,a+w-r,b+h);x.lineTo(a+r,b+h);x.quadraticCurveTo(a,b+h,a,b+h-r);x.lineTo(a,b+r);x.quadraticCurveTo(a,b,a+r,b);x.closePath()}
window.startToday=startToday;window.startManual=startManual;window.render=render;window.markCard=markCard;window.speakWord=speakWord;window.checkAnswer=checkAnswer;window.next=next;window.downloadCard=downloadCard;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;startManual()});$('#grade').onchange=()=>{refreshUnits();updateTodayPanel()};$('#unit').onchange=updateTodayPanel;$('#limit').onchange=()=>{};$('#start').onclick=startManual;$('#startToday').onclick=startToday;document.addEventListener('keydown',e=>{if(e.key==='Enter'&&currentTask()!=='cards'&&$('#answer')&&!state.checked)checkAnswer();else if(e.key==='Enter'&&state.checked)next()});options();stats();showWelcome();
